service:
  name: ipuresults

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  env: ${file(./vars.env.js):getEnvVars}

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-south-1
  timeout: 15
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
  environment:
    DB_HOST: ${self:custom.env.DB_HOST}
    DB_USER: ${self:custom.env.DB_USER}
    DB_PASSWORD: ${self:custom.env.DB_PASSWORD}
    BUCKET_NAME: ${self:custom.env.BUCKET_NAME}
    START_URL: ${self:custom.env.START_URL}

functions:
  downloadPdf:
    handler: handler.downloadPdf
    events:
      - schedule: rate(1 minute)
  fetchLinks:
    handler: handler.fetchLinks
    events:
      - schedule: rate(1 hour)
  convertToTxt:
    handler: handler.convertToTxt
    events:
      - schedule: rate(1 minute)